In [3]:
from flask import Flask, request, render_template, render_template_string
import pandas as pd
from glob import glob
import folium
import json
import requests
import os
import base64
import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt
from bs4 import BeautifulSoup

# My functions
import plotmap as plotmap
import mapping
import mapnavbar

In [23]:
# countries = {}
# for i in glob('./static/original/??_dataframe*.csv.gz'):
#     country_code = os.path.basename(i)[:2]
#     countries[country_code] = mapping.convert_country_code(country_code)

In [24]:
# print(countries["QA"])

In [11]:
createMap('QA')

In [4]:
def createMap(countrycode):
    countrycode=countrycode
    path = glob('./static/simplified/{}.csv.gz'.format(countrycode))[0]
    df = pd.read_csv(path)
    country = mapping.convert_country_code(countrycode)

    bmap = plotmap.BaseMap(data=df, shapefile='../places.geojson')
    
    bmap.createGroup('Gender')
    g = plotmap.Geojson(bmap, 'Gender', 'Total', country, locationcol='citizenship')
    g.colorMap(column1='Total_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
#     g.addAbsolute(["Male_mau"],'')
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)

    g = plotmap.Geojson(bmap, 'Gender', 'Male', country, locationcol='citizenship')
    g.colorMap(column1='Male_mau')
    #g.colorMap(column1='Male_mau', threshold_min1=1001)
    g.createMap(key='name')
    
    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

   
    g.addInfoBox(countrycode)

    g = plotmap.Geojson(bmap, 'Gender', 'Female', country,  locationcol='citizenship')
    g.colorMap(column1='Female_mau')
    #g.colorMap(column1='Female_dau', threshold_min1=1001)
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    #create os group
    bmap.createGroup('OS') 
    
    g = plotmap.Geojson(bmap, 'OS', 'iOS', country, locationcol='citizenship')
    g.colorMap(column1='iOS_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")
    

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    g = plotmap.Geojson(bmap, 'OS', 'Android', country, locationcol='citizenship')
    g.colorMap(column1='Android_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    g = plotmap.Geojson(bmap, 'OS', 'Other', country, locationcol='citizenship')
    g.colorMap(column1='Other_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    #create os group
    bmap.createGroup('Scholarities') 
    
    g = plotmap.Geojson(bmap, 'Scholarities', 'No Degree', country, locationcol='citizenship')
    g.colorMap(column1='No_Degree_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    g = plotmap.Geojson(bmap, 'Scholarities', 'High School', country, locationcol='citizenship')
    g.colorMap(column1='High_School_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    g = plotmap.Geojson(bmap, 'Scholarities', 'Graduated', country, locationcol='citizenship')
    g.colorMap(column1='Graduated_mau')
    g.createMap(key='name')

    g.addValue(["Male_mau", "Female_mau"], " of the emigrating expats are males")
    g.addValue(['Female_mau', "Male_mau", ], " of the emigrating expats are females<br><hr>")

    g.addValue(["Other_mau", "iOS_mau", "Android_mau"], " of the emigrating expats are using other OS")
    g.addValue(["iOS_mau", "Other_mau", "Android_mau"], " of the emigrating expats are using iOS")
    g.addValue(["Android_mau", "iOS_mau", "Other_mau"], " of the emigrating expats are using Android<br><hr>")

    g.addValue(["No_Degree_mau", "Graduated_mau", "High_School_mau"], " of the emigrating expats do not have a degree")
    g.addValue(["Graduated_mau", "High_School_mau", "No_Degree_mau"], " of the emigrating expats graduated from college")
    g.addValue(["High_School_mau", "Graduated_mau", "No_Degree_mau"], " of the emigrating expats have a high school degree")

    g.addInfoBox(countrycode)
    
    bmap.groupedLayerControl(['Gender','OS','Scholarities'])
    mapnavbar.FloatImage().add_to(bmap.map)
    m=bmap.map
    m.save('templates/ImmigrationMaps/{}.html'.format(countrycode))
#     m.save('{}.html'.format(countrycode))

In [5]:
for f in glob('./static/simplified/??*.csv.gz'):
    country_code = os.path.basename(f)[:2]
    createMap(country_code)

In [13]:
path = glob('./static/simplified/{}.csv.gz'.format('QA'))[0]
df = pd.read_csv(path)
df

,citizenship,Other_dau,iOS_dau,Android_dau,Other_mau,iOS_mau,Android_mau,13-14_dau,15-19_dau,15-24_dau,...,Female_dau,Total_mau,Male_mau,Female_mau,Graduated_dau,High_School_dau,No_Degree_dau,Graduated_mau,High_School_mau,No_Degree_mau
0,Locals,405266,11769,24439,570000,26000,36000,666,12429,68161,...,112038,630000,420000,160000,213329,63736,150555,270000,84000,260000
1,All,444011,207961,621693,760000,280000,830000,374,34804,224572,...,260830,1800000,1400000,390000,466737,162034,583591,620000,220000,950000
2,India,97334,45068,158280,160000,63000,210000,333,4035,37720,...,31678,420000,370000,51000,133238,37743,120635,180000,51000,190000
3,Kenya,8058,1079,10227,12000,1500,13000,0,997,699,...,7013,27000,16000,9800,8627,3133,6983,11000,4000,12000
4,Nigeria,816,833,2293,1400,1000,3000,0,0,285,...,583,5000,3900,1000,1889,599,639,2700,1000,1600
5,Cameroon,-1,-1,-1,1000,1000,1000,0,997,997,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
6,Philippines,47682,43576,94252,87000,56000,120000,332,2808,13955,...,100934,250000,110000,140000,88058,31896,53846,110000,42000,96000
7,Cuba,-1,-1,-1,1000,1000,1000,0,0,498,...,799,1000,1000,1000,-1,-1,-1,1000,1000,1000
8,Ethiopia,8692,832,4703,14000,1000,5900,0,437,2872,...,5400,21000,12000,7900,2719,1424,9849,3400,2100,15000
9,Haiti,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
10,Spain,285,999,332,1000,1000,1000,0,0,0,...,499,1200,1000,1000,998,0,142,1000,1000,1000
11,France,473,713,914,1800,1000,1200,0,997,374,...,1035,3800,2600,1600,1010,499,999,1400,1000,2000
12,Germany,-1,-1,-1,1000,1000,1000,0,0,997,...,332,1000,1000,1000,-1,-1,-1,1000,1000,1000
13,Switzerland,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
14,Hungary,-1,-1,-1,1000,1000,1000,0,0,997,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
15,Ireland,-1,-1,-1,1000,1000,1000,0,0,0,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
16,Italy,249,664,856,1000,1000,1000,0,997,498,...,570,1500,1100,1000,635,0,333,1000,1000,1000
17,Poland,-1,-1,-1,1000,1000,1000,0,0,0,...,498,1000,1000,1000,-1,-1,-1,1000,1000,1000
18,Canada,199,999,249,1000,1000,1000,0,0,499,...,666,1800,1100,1000,855,0,333,1100,1000,1000
19,China,-1,-1,-1,1000,1000,1000,0,0,0,...,499,1000,1000,1000,-1,-1,-1,1000,1000,1000
20,Puerto Rico,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
21,Brazil,492,374,452,1600,1000,1100,0,499,249,...,666,3600,2700,1000,959,222,899,1200,1000,2000
22,Indonesia,5371,1649,5868,13000,2200,7900,0,499,2171,...,7058,23000,10000,12000,2975,1090,7603,5000,2400,15000
23,South Africa,199,832,624,1000,1000,1000,0,0,0,...,761,2600,1500,1100,1028,332,222,1200,1000,1000
24,Zimbabwe,-1,-1,-1,1000,1000,1000,0,0,997,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
25,Ghana,1289,454,1338,2200,1000,2200,0,997,999,...,997,4700,4300,1000,1285,699,1735,1500,1000,2500
26,Uganda,2899,666,3412,4600,1000,4800,0,0,481,...,1940,9700,7200,2700,2932,866,2630,4400,1300,3900
27,Colombia,-1,-1,-1,1000,1000,1000,0,0,0,...,332,1000,1000,1000,-1,-1,-1,1000,1000,1000
28,Dominican Republic,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
29,El Salvador,-1,-1,-1,1000,1000,1000,0,0,0,...,498,1000,1000,1000,-1,-1,-1,1000,1000,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Luxembourg,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
62,Malta,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
63,Monaco,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
64,Slovakia,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
65,Slovenia,-1,-1,-1,1000,1000,1000,0,0,0,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
66,Mexico,-1,-1,-1,1000,1000,1000,0,0,0,...,249,1000,1000,1000,-1,-1,-1,1000,1000,1000
67,Saudi Arabia,449,639,1438,1200,1600,2200,0,997,555,...,599,4700,3300,1300,1238,899,815,2300,1000,1700
68,Russia,-1,-1,-1,1000,1000,1000,0,0,0,...,332,1000,1000,1000,-1,-1,-1,1000,1000,1000
69,Israel,-1,-1,-1,1000,1000,1000,0,0,997,...,999,1000,1000,1000,-1,-1,-1,1000,1000,1000
70,Argentina,-1,-1,-1,1000,1000,1000,0,0,0,...,332,1000,1000,1000,-1,-1,-1,1000,1000,1000
71,Chile,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
72,Rwanda,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
73,Venezuela,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
74,Malaysia,333,824,1039,1000,1100,1300,0,0,332,...,549,2900,1800,1100,1178,332,666,1500,1000,1000
75,Romania,499,664,856,1000,1000,1000,0,0,0,...,666,1200,1000,1000,777,0,499,1000,1000,1000
76,South Korea,0,499,399,1000,1000,1000,0,0,0,...,333,1500,1000,1000,249,997,399,1000,1000,1000
77,Serbia,0,888,624,1000,1000,1000,0,0,498,...,726,1200,1000,1000,888,997,499,1000,1000,1000
78,Vietnam,428,0,997,1000,1000,1000,0,0,0,...,0,1600,1200,1000,0,0,549,1000,1000,1100
79,Peru,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
80,Belgium,-1,-1,-1,1000,1000,1000,0,0,0,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
81,Zambia,-1,-1,-1,1000,1000,1000,0,997,997,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
82,Honduras,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
83,Finland,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
84,Latvia,-1,-1,-1,1000,1000,1000,0,0,0,...,0,1000,1000,1000,-1,-1,-1,1000,1000,1000
85,Jordan,1559,6064,6013,2600,9300,7000,0,416,1506,...,6205,18000,9700,8100,8079,1562,3270,9500,2500,5700
86,Lebanon,1099,5094,3272,1800,6900,4000,0,997,570,...,3674,12000,6600,4900,4674,1199,3235,5900,1500,4700
87,Nicaragua,-1,-1,-1,1000,1000,1000,0,0,0,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
88,Algeria,687,1010,1595,1100,1300,2100,0,0,0,...,807,4200,2700,1500,1359,0,1295,1700,1000,1900
89,Kuwait,-1,-1,-1,1000,1000,1000,0,0,997,...,997,1000,1000,1000,-1,-1,-1,1000,1000,1000
90,Qatar,0,249,1199,1000,1000,1200,0,997,498,...,0,2300,1100,1000,855,498,0,1100,1000,1000